workspace:
  base: /go
  path: src/github.com/joshdvir/telegram-middleman-bot
pipeline:

  release:
    image: golang:alpine
    secrets: [ github_token ]
    commands:
      - apk add git bash curl
      - go get ./...
      - curl -sL https://git.io/goreleaser | bash -s -- --snapshot
      - mkdir build
      - cp Dockerfile build/
      - cp dist/linux_amd64/telegram-middleman-bot build/
    when:
      event: [ push, tag ]

  docker:
    image: plugins/docker:latest
    repo: joshdvir/telegram-middleman-bot
    tag:
      - "${DRONE_BUILD_NUMBER}"
      - "latest"
    force_tag: true
    context: build
    file: Dockerfile
    secrets: [ docker_username, docker_password ]
    when:
      event: [ push, tag ]