workspace:
  base: /go
  path: src/bitbucket.org/joshdvir/telegram-middleman-bot

  release:
    image: golang:alpine
    secrets: [ github_token ]
    commands:
      - apk add git bash curl
      - go get ./...
      - curl -sL https://git.io/goreleaser | bash --snapshot
    when:
      event: [ push, tag ]

  docker:
    image: plugins/docker:latest
    repo: joshdvir/telegram-middleman-bot
    tag:
      - "${DRONE_BUILD_NUMBER}"
      - "latest"
    force_tag: true
    file: Dockerfile
    secrets: [ docker_username, docker_password ]
    when:
      event: [ push, tag ]